application: awesome-sphere-88306
version: 1-0
runtime: python27
api_version: 1
threadsafe: true

handlers:
# main webpage handler
- url: /
  static_files: static/mainpage.html
  upload: static/mainpage.html

- url: /index\.html
  static_files: static/mainpage.html
  upload: static/mainpage.html

- url: /demo
  script: demo.application

- url: /signin
  static_files: static/signin.html
  upload: static/signin.html

- url: /(login|logout)$
  script: auth.application

# resources handlers
- url: /stylesheets/(.*\.(less|css))$
  static_files: static/stylesheets/\1
  upload: static/stylesheets/(.*\.(less|css))$

- url: /scripts/(.*\.(js|coffee))$
  static_files: static/scripts/\1
  upload: static/scripts/(.*\.(js|coffee))$

- url: /fonts/(.*\.(ttf))$
  static_files: static/fonts/\1
  upload: static/fonts/(.*\.(ttf))$

# api calls
- url: /api/.*
  script: api.application


libraries:
- name: webapp2
  version: latest
